version: "3"
services:
  peer0:
    build: ..
    depends_on:
      - mongo0
      - redis0
    ports:
      - "3000:3000"
    environment:
      - HOST=http://peer0:3000
      - PORT=3000
      - CENTER=-34.574985,-58.482189
      - CITY="Buenos Aires"
      - COUNTRY=Argentina
      - MONGO_URI=mongodb://mongo0:27018/peersEatDB
      - INITIAL_PEER=
      - REDIS_URI=redis://redis0:6380
  mongo0:
    image: mongo
    command: mongod --port 27018
    ports:
      - "27018:27018"
  redis0:
    image: redis
    command: redis-server --port 6380
    ports:
      - "6380:6380"
